name: pre-commit

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: set PY
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name : Run Python test
      run: pytest test_barchart.py
